// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cv_h1_tv_rcpp
arma::mat cv_h1_tv_rcpp(SEXP YY, SEXP FF, SEXP KMAX, SEXP MM, SEXP BD);
RcppExport SEXP _SemiDMFMC_cv_h1_tv_rcpp(SEXP YYSEXP, SEXP FFSEXP, SEXP KMAXSEXP, SEXP MMSEXP, SEXP BDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type YY(YYSEXP);
    Rcpp::traits::input_parameter< SEXP >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< SEXP >::type KMAX(KMAXSEXP);
    Rcpp::traits::input_parameter< SEXP >::type MM(MMSEXP);
    Rcpp::traits::input_parameter< SEXP >::type BD(BDSEXP);
    rcpp_result_gen = Rcpp::wrap(cv_h1_tv_rcpp(YY, FF, KMAX, MM, BD));
    return rcpp_result_gen;
END_RCPP
}
// cv_h2_tv_rcpp
NumericVector cv_h2_tv_rcpp(SEXP MM, SEXP FFF, SEXP KMAX, double KK, SEXP TT, SEXP WW);
RcppExport SEXP _SemiDMFMC_cv_h2_tv_rcpp(SEXP MMSEXP, SEXP FFFSEXP, SEXP KMAXSEXP, SEXP KKSEXP, SEXP TTSEXP, SEXP WWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type MM(MMSEXP);
    Rcpp::traits::input_parameter< SEXP >::type FFF(FFFSEXP);
    Rcpp::traits::input_parameter< SEXP >::type KMAX(KMAXSEXP);
    Rcpp::traits::input_parameter< double >::type KK(KKSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< SEXP >::type WW(WWSEXP);
    rcpp_result_gen = Rcpp::wrap(cv_h2_tv_rcpp(MM, FFF, KMAX, KK, TT, WW));
    return rcpp_result_gen;
END_RCPP
}
// lnf_gc_tv
double lnf_gc_tv(SEXP ZZZ, SEXP TTT, SEXP T0);
RcppExport SEXP _SemiDMFMC_lnf_gc_tv(SEXP ZZZSEXP, SEXP TTTSEXP, SEXP T0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ZZZ(ZZZSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TTT(TTTSEXP);
    Rcpp::traits::input_parameter< SEXP >::type T0(T0SEXP);
    rcpp_result_gen = Rcpp::wrap(lnf_gc_tv(ZZZ, TTT, T0));
    return rcpp_result_gen;
END_RCPP
}
// lnf_gc_tv_tar
double lnf_gc_tv_tar(SEXP ZZZ, SEXP TTT, SEXP TTT0, SEXP T0);
RcppExport SEXP _SemiDMFMC_lnf_gc_tv_tar(SEXP ZZZSEXP, SEXP TTTSEXP, SEXP TTT0SEXP, SEXP T0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ZZZ(ZZZSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TTT(TTTSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TTT0(TTT0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type T0(T0SEXP);
    rcpp_result_gen = Rcpp::wrap(lnf_gc_tv_tar(ZZZ, TTT, TTT0, T0));
    return rcpp_result_gen;
END_RCPP
}
// lnf_tgc_tv
double lnf_tgc_tv(SEXP ZZZ, SEXP TTT, SEXP T0);
RcppExport SEXP _SemiDMFMC_lnf_tgc_tv(SEXP ZZZSEXP, SEXP TTTSEXP, SEXP T0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ZZZ(ZZZSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TTT(TTTSEXP);
    Rcpp::traits::input_parameter< SEXP >::type T0(T0SEXP);
    rcpp_result_gen = Rcpp::wrap(lnf_tgc_tv(ZZZ, TTT, T0));
    return rcpp_result_gen;
END_RCPP
}
// lnf_tgc_tv_lt
NumericVector lnf_tgc_tv_lt(SEXP ZZZ, SEXP TTT, SEXP T0);
RcppExport SEXP _SemiDMFMC_lnf_tgc_tv_lt(SEXP ZZZSEXP, SEXP TTTSEXP, SEXP T0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ZZZ(ZZZSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TTT(TTTSEXP);
    Rcpp::traits::input_parameter< SEXP >::type T0(T0SEXP);
    rcpp_result_gen = Rcpp::wrap(lnf_tgc_tv_lt(ZZZ, TTT, T0));
    return rcpp_result_gen;
END_RCPP
}
// lnf_tgc_tv_tar
double lnf_tgc_tv_tar(SEXP ZZZ, SEXP TTT, SEXP TTT0, SEXP T0);
RcppExport SEXP _SemiDMFMC_lnf_tgc_tv_tar(SEXP ZZZSEXP, SEXP TTTSEXP, SEXP TTT0SEXP, SEXP T0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ZZZ(ZZZSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TTT(TTTSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TTT0(TTT0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type T0(T0SEXP);
    rcpp_result_gen = Rcpp::wrap(lnf_tgc_tv_tar(ZZZ, TTT, TTT0, T0));
    return rcpp_result_gen;
END_RCPP
}
// lnf_tgc_tv_tar_lt
NumericVector lnf_tgc_tv_tar_lt(SEXP ZZZ, SEXP TTT, SEXP TTT0, SEXP T0);
RcppExport SEXP _SemiDMFMC_lnf_tgc_tv_tar_lt(SEXP ZZZSEXP, SEXP TTTSEXP, SEXP TTT0SEXP, SEXP T0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ZZZ(ZZZSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TTT(TTTSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TTT0(TTT0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type T0(T0SEXP);
    rcpp_result_gen = Rcpp::wrap(lnf_tgc_tv_tar_lt(ZZZ, TTT, TTT0, T0));
    return rcpp_result_gen;
END_RCPP
}
// npest_tv_rcpp
arma::mat npest_tv_rcpp(double UU, double HH, arma::mat YY, arma::mat FF, arma::mat ZZ);
RcppExport SEXP _SemiDMFMC_npest_tv_rcpp(SEXP UUSEXP, SEXP HHSEXP, SEXP YYSEXP, SEXP FFSEXP, SEXP ZZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type UU(UUSEXP);
    Rcpp::traits::input_parameter< double >::type HH(HHSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type YY(YYSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ZZ(ZZSEXP);
    rcpp_result_gen = Rcpp::wrap(npest_tv_rcpp(UU, HH, YY, FF, ZZ));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SemiDMFMC_cv_h1_tv_rcpp", (DL_FUNC) &_SemiDMFMC_cv_h1_tv_rcpp, 5},
    {"_SemiDMFMC_cv_h2_tv_rcpp", (DL_FUNC) &_SemiDMFMC_cv_h2_tv_rcpp, 6},
    {"_SemiDMFMC_lnf_gc_tv", (DL_FUNC) &_SemiDMFMC_lnf_gc_tv, 3},
    {"_SemiDMFMC_lnf_gc_tv_tar", (DL_FUNC) &_SemiDMFMC_lnf_gc_tv_tar, 4},
    {"_SemiDMFMC_lnf_tgc_tv", (DL_FUNC) &_SemiDMFMC_lnf_tgc_tv, 3},
    {"_SemiDMFMC_lnf_tgc_tv_lt", (DL_FUNC) &_SemiDMFMC_lnf_tgc_tv_lt, 3},
    {"_SemiDMFMC_lnf_tgc_tv_tar", (DL_FUNC) &_SemiDMFMC_lnf_tgc_tv_tar, 4},
    {"_SemiDMFMC_lnf_tgc_tv_tar_lt", (DL_FUNC) &_SemiDMFMC_lnf_tgc_tv_tar_lt, 4},
    {"_SemiDMFMC_npest_tv_rcpp", (DL_FUNC) &_SemiDMFMC_npest_tv_rcpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SemiDMFMC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
