# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cv_h1_tv_rcpp <- function(YY, FF, KMAX, MM, BD) {
    .Call(`_SemiDMFMC_cv_h1_tv_rcpp`, YY, FF, KMAX, MM, BD)
}

cv_h2_tv_rcpp <- function(MM, FFF, KMAX, KK, TT, WW) {
    .Call(`_SemiDMFMC_cv_h2_tv_rcpp`, MM, FFF, KMAX, KK, TT, WW)
}

lnf_gc_tv <- function(ZZZ, TTT, T0) {
    .Call(`_SemiDMFMC_lnf_gc_tv`, ZZZ, TTT, T0)
}

lnf_gc_tv_tar <- function(ZZZ, TTT, TTT0, T0) {
    .Call(`_SemiDMFMC_lnf_gc_tv_tar`, ZZZ, TTT, TTT0, T0)
}

lnf_tgc_tv <- function(ZZZ, TTT, T0) {
    .Call(`_SemiDMFMC_lnf_tgc_tv`, ZZZ, TTT, T0)
}

lnf_tgc_tv_lt <- function(ZZZ, TTT, T0) {
    .Call(`_SemiDMFMC_lnf_tgc_tv_lt`, ZZZ, TTT, T0)
}

lnf_tgc_tv_tar <- function(ZZZ, TTT, TTT0, T0) {
    .Call(`_SemiDMFMC_lnf_tgc_tv_tar`, ZZZ, TTT, TTT0, T0)
}

lnf_tgc_tv_tar_lt <- function(ZZZ, TTT, TTT0, T0) {
    .Call(`_SemiDMFMC_lnf_tgc_tv_tar_lt`, ZZZ, TTT, TTT0, T0)
}

npest_tv_rcpp <- function(UU, HH, YY, FF, ZZ) {
    .Call(`_SemiDMFMC_npest_tv_rcpp`, UU, HH, YY, FF, ZZ)
}

